[package]
name = "myproject2"
version = "0.1.0"
authors = ["David Rinck <rinckd@atonix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
